### ISSUE TITLE
ERC721 unnecessarily emits an `Approval` event on transfers

### ISSUE THREAD

**Issue by abandeali1** [OpenZeppelin/openzeppelin-solidity#1038]
## 🎉 Description

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

Currently, an `Approval` event is unnecessarily emitted when a transfer that resets an approval occurs. See comments towards the end of https://github.com/ethereum/EIPs/pull/841 clarifying that an `Approval` event should not be emitted in this scenario.

**Comment by shrugs** [comment]
The 841 thread can't be used for identifying the standard's requirements, since they've been outdated by various updates to the primary spec at http://eips.ethereum.org/EIPS/eip-721

The text of 721:

```
    /// @dev This emits when ownership of any NFT changes by any mechanism.
    ///  This event emits when NFTs are created (`from` == 0) and destroyed
    ///  (`to` == 0). Exception: during contract creation, any number of NFTs
    ///  may be created and assigned without emitting Transfer. At the time of
    ///  any transfer, the approved address for that NFT (if any) is reset to none.
    event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId);

    /// @dev This emits when the approved address for an NFT is changed or
    ///  reaffirmed. The zero address indicates there is no approved address.
    ///  When a Transfer event emits, this also indicates that the approved
    ///  address for that NFT (if any) is reset to none.
    event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId);
```

Specifically, `At the time of any transfer, the approved address for that NFT (if any) is reset to none.` followed by `This emits when the approved address for an NFT is changed or reaffirmed.` doesn't provide any special case for approval changes as a side effect of transfers.

Let me know if you interpret that differently

**Comment by shrugs** [comment]
@abandeali1 ah, sorry for not checking the thread directly. didn't realize it was fulldecent that had commented on the distinction. I do think my interpretation makes much more sense than the special case for transfer-initiated approval resets, but I'm not sure how flexible the standard is, now that it's been finalized. What are the pros towards _not_ emitting the Approval event? An indexer trying to ascertain the full approval log of a token must also understand the implicit side effects of a Transfer event if they are to build an accurate history.

Anyway, the spec is confusing in this case, and the language should be updated to very clearly state the intention. I've reached out to @fulldecent in the ETH-NFt chat to get his understanding.

**Comment by abandeali1** [comment]
I just find it to be redundant - you're not gaining any extra information that you don't already get from the `Transfer` event (and of course, this costs gas). ERC20 doesn't emit an `Approval` event every time `transferFrom` is called either.

**Comment by shrugs** [comment]
I can understand that, yeah. Looks like fulldecent has already approved and pushed the oxcert change, so I'll take that as the intent of the spec. It would be nice to get the wording clearer in the future.

**Comment by fulldecent** [comment]
Hello all, I'm dropping by from a note in NFT/Lobby. I can see that a specific word in the spec is ambiguous and has lead to two different interpretations:

```solidity
/// @dev This emits when the approved address for an NFT is changed or
///  reaffirmed. The zero address indicates there is no approved address.
///  When a Transfer event emits, this also indicates that the approved
///  address for that NFT (if any) is reset to none.
event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId);
```

It would have been more clear to say "It is unnecessary to emit Approval when a transfer occurs," and that is the intention of these words in the standard.

I can see the problem is my poor choice of "this also indicates" -- where "this" is the Transfer.

To be clear, an implementation that emits a redundant Approval event is compliant with the standard.

---

If OZ will accept this interpretation of the standard and make the change, then I would appreciate if anybody can propose an errata for 721 to clarify this.
