### ISSUE TITLE
Multiple Inheritance Issue: TypeError: Linearization of inheritance graph impossible

### ISSUE THREAD

**Issue by madan-ideas2it** [OpenZeppelin/openzeppelin-solidity#1124]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/4c6575bf2fdf97af517b9c1aea886125bab8c4af/contracts/crowdsale/validation/WhitelistedCrowdsale.sol#L11

When we inherit a contract with Whitelisted and other types of crowdsales, it causes the above said issue.

The fix was to swap the order of Whitelist and Crowdsale. Hence changing 

contract WhitelistedCrowdsale is Whitelist, Crowdsale {

to 

contract WhitelistedCrowdsale is Crowdsale, Whitelist {

Fixes the issue

**Comment by nventuro** [comment]
This is because Solidity supports multiple inheritance through [C3 linearization](https://solidity.readthedocs.io/en/v0.4.24/contracts.html#multiple-inheritance-and-linearization), disallowing some inheritance graphs. While annoying, there's not much we can do about it, and as far as I know, there aren't any cases in OZ where this prevents compilation.

**Comment by madan-ideas2it** [comment]
It breaks compilation for

contract XXX is CappedCrowdsale, IndividuallyCappedCrowdsale, TimedCrowdsale, WhitelistedCrowdsale

**Comment by nventuro** [comment]
Hm, you're right. I was also able to build that one by changing the inheritance order in `IndividuallyCappedCrowdsale` to contract `Ownable, Crowdsale`. I believe inheriting from `Crowdsale` last will give us the most flexibility. Thanks @madan-ideas2it!
