### ISSUE TITLE
API - always allow contracts to trigger pull payments

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1132]
As of `v1.11`, only the recipient of funds can trigger a withdrawal in `PullPayments`: 

```
function withdrawPayments() public {
  address payee = msg.sender;
  escrow.withdraw(payee);
}
```

The same thing happens in `SplitPayment`:
```
function claim() public {
  address payee = msg.sender;
  ...
}
```

This means interactions from contracts with these interfaces are limited, since a) they won't be able to receive their funds (unless the respective function call is coded into them), and most importantly b) they won't be able to trigger transactions for another recipient (e.g. have a contract schedule pull payments and another one then execute them in sequence, abstracting the whole thing away from end users).

I think all of these functions should provide an `address recipient` parameter, and `msg.sender` should never be used for this purpose (and only to determine origin, e.g. when doing access control).

**Comment by elopio** [comment]
This could be very error prone, because the address passed as an argument could have a typo and then the result could be catastrophic. Using msg.sender is a safety mechanism, because the user proved to have access to the account in order to send the transaction.

An idea that came to mind is that just like with tokens, this should happen with something like the allowance, that explicitly gives permission to others to send and receive. 

I think we should experiment with this for 3.0, not now. Let's keep this one open for discussion.

**Comment by frangio** [comment]
>the address passed as an argument could have a typo and then the result could be catastrophic

This is sometimes true, and I love the idea of using `msg.sender` as a safety mechanism, but it's not relevant for the case of `SplitPayment`, because the critical use of the address has already passed. I think we can use that as a heuristic. When a typo in the address does not have critical consequences, we should use address arguments for maximum flexibility; otherwise we should use `msg.sender`.

**Comment by frangio** [comment]
Assigning myself as we agreed offline that I'll be leading the signatures part of the API review.

**Comment by nventuro** [comment]
@frangio that sounds like a great starting point - could you dig into the code and provide some examples, to better understand each case?

**Comment by nventuro** [comment]
#1234 presents a somewhat related situation, anyone (not just the beneficiary) can trigger a release of a `TokenTimelock`. This allows for a contract to be a beneficiary, despite not having a public function that calls `release`, and for any contract to also trigger said release.

**Comment by frangio** [comment]
Agreed that it's the same situation. @ddbit would you mind expanding on what you think is the problem with anyone being able to release the funds?

**Comment by ddbit** [comment]
It does not seem a great problem because funds always move to the legit owner, however allowing everyone to trigger such a transfer is against the security principle of least authority. Think of a use case where the holdings grant some dividends as long as they are locked in the contract. The user is forced to wait the timelock before withdraw, but what if he may prefer to keep holding even after the timelock expires? With the current implementation the user doesn't have this option.

**Comment by frangio** [comment]
@ldub The use case you presented is interesting, although I have a hard time picturing the actual implementation for such dividends. However, I think this argument is not strong enough when compared to the potential enabled by allowing anyone to release funds or trigger pending payments. It means that you can set any address as the beneficiary without imposing constraints on it (e.g. being able to call `release` on a specific contract), and this leads to great composability.

If someone really needs to control when a `release` is trigged, they can opt-in to this behavior by using a contract as the beneficiary that rejects funds unless a given condition is satisfied (such as being the originator of the release).
