### ISSUE TITLE
Add a leading underscore to internal functions

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1176]
It would be good to add an indication to function names when they are private. Let's add an _ in front of the name.

**Comment by elopio** [comment]
Should we also add an _ to internal functions? They can be called from contracts that are inheriting from the one that includes the declaration. I'm not sure if _ in those cases gives the right information to the readers.

**Comment by frangio** [comment]
It's not clear to me either, but I think I prefer underscore for `internal` functions as well. In that case the information that we want to convey is "this is not externally reachable".

Leaving out the underscore makes sense if what we want to convey is "this is neither part of the internal nor external API, so do not use it", but in that case we should be using `private` functions which mean exactly that, and are statically checked. @elopio Can you think of a case where we'd have to make a function `internal` without it actually being a part of the internal API?

**Comment by frangio** [comment]
Although an exception to the underscore rule would be libraries' internal functions.

**Comment by frangio** [comment]
@nventuro reminded me that we use the underscore prefix for `internal` functions such as `_mint` and `_burn` in `StandardToken` because we later expose them through non-prefixed `external` functions. It's not possible to change visibility so we have to have the underscore.

For consistency, all `internal` functions should have the underscore prefix.

cc @elopio
