### ISSUE TITLE
Improve constants inline documentation

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1182]
As noted by @ldub [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1086#discussion_r208780472), some of our comments (specially those related to ERC165 ids) are not consistent in style, nor is the current style appropriate in a Solidity context. 

We should settle on a style and have current code conform to it.

**Comment by balajipachai** [comment]
@nventuro 
I am willing to work on this, however, I am not getting what exactly has to be done?
Could you assist me on the same, so that I start working on it?

**Comment by frangio** [comment]
Hi @balajipachai! This is about the comments for `constant` variables throughout the project. Quoting the original issues mentioned in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1086#discussion_r208780472:
> 1. Why does the comment go *after* the field instead of before it?
> 2. Some places in this repo ([link1]) use a natspec-style double asterisk comment `/**` even though its after the field and thus not natspec
> 3. We are using triple equals in a solidity context ([link1] [link2])

[link1]: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/4c6575bf2fdf97af517b9c1aea886125bab8c4af/contracts/introspection/SupportsInterfaceWithLookup.sol#L14
[link2]: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/b120b9aff79d04352778d4e5fd773d987727e1cc/contracts/token/ERC721/ERC721Basic.sol#L14

So we have to look at all the `constant`s defined throughout the project and then: 1. move the comment before the variable, 2. make sure it's using single asterisk (i.e. `/*` instead of `/**`), and use double equals (`==`) instead of triple equals (`===`).

**Comment by balajipachai** [comment]
@nventuro & @frangio 
Fixed the #1182 - Improve constants inline documentation
Opened a PR #1707
