### ISSUE TITLE
TokenTimelock is not working in rinkeby

### ISSUE THREAD

**Issue by littleanti** [OpenZeppelin/openzeppelin-solidity#1222]
I do not know why TokenTimelock is not working in testnet. 

Contract is completely made. 
I put token to contract address, and check release time. 
But release is not working forever.

**Comment by nventuro** [comment]
Hi @littleanti! Could you provide some more information on your setup and the issue you're experiencing? Thanks!

**Comment by littleanti** [comment]
![image](https://user-images.githubusercontent.com/16498206/44560567-51d4e680-a78b-11e8-93bd-e3a0e8e47c7e.png)

Thank you for your reply.
Right bottom side of screenshot. Current block.timestamp is 1535075270 and releaseTime is 1534793840.
However, when I clicked the release function in TokenTimelock. It returns gas estimation failed.

Btw, is the send ether to TokenTimelock failure normal?
I cannot send ETH to TokenTimelock for transaction fee.

Thank you.

**Comment by nventuro** [comment]
Does the token actually own tokens? Note lines 44 and 45:

```
uint256 amount = token.balanceOf(address(this));
require(amount > 0);
```

You won't be able to send ether to a `TokenTimelock` because it doesn't have any payable functions. You shouldn't need to, however, since the transaction fee will be payed for by the account that initiated the transaction (yours, as opposed to the contract you're calling).

**Comment by littleanti** [comment]
Thank you for reply. 

![image](https://user-images.githubusercontent.com/16498206/44594873-51c3fd80-a802-11e8-8258-d8afcf59eea0.png)

Yes. that token is own by Contract, and either msg.sender.

Yoon.
