### ISSUE TITLE
Apply correct code style in Solidity (minor)

### ISSUE THREAD

**Issue by kabl** [OpenZeppelin/openzeppelin-solidity#1223]
## 🎉 Description

Apply correct code style. As described here: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/CODE_STYLE.md

OZ solidity code uses Use 2 spaces per indentation. But in the CODE_STYLE.md the Solidity official style guide is referenced. And code indention is defined as follow: "...Use 4 spaces per indentation level..."

- [] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

- Which version of OpenZeppelin are you using?
Current version

**Comment by nventuro** [comment]
This has already been discussed in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/152. 

My stance is that our style is actually better than the one suggested by the Solidity team, mainly because any Solidity project will also have JavaScript code, both for testing and for interacting with smart contracts (be it a deployment script, a dApp, etc.). There is a strong tradition in JS-land of using 2 spaces instead of 4, and Solidity itself has been inspired by JavaScript: I'd rather use the same style rules in both my tests/scripts as in the smart contract code. IMO, we should push for Solidity to change _their_ recommended style guide.

**Comment by shrugs** [comment]
closing as duplicate; let's discuss in #152
