### ISSUE TITLE
Compilation error after updating OpenZeppelin

### ISSUE THREAD

**Issue by PShivam92** [OpenZeppelin/openzeppelin-solidity#1259]
## 🎉 After updation of OpenZeppelin getting error  

pragma solidity ^0.4.18;

import 'github.com/OpenZeppelin/openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol';

contract MyToken is MintableToken {
     string public constant name;
     string public constant symbol;
     uint8 public constant decimals;
}

```
github.com/OpenZeppelin/openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol:45:14: ParserError: Expected token Semicolon got 'LParen' emit Mint(_to, _amount);
```

**Comment by nventuro** [comment]
Are you sure you're using the latest compiler? The `emit` keyword is new, and from your example it looks like you may still be running 0.4.18.

**Comment by PShivam92** [comment]
Code is written using 0.4.18 but its not compiling with compiler 0.4.18 nor with latest that is 0.4.24

**Comment by nventuro** [comment]
Which version are you using then? `emit` was introduced in 0.4.21 if I recall correctly.

**Comment by PShivam92** [comment]
Im not using emit in my code ,its saying the error is in openzeppelin and before the updation  code was working correctly .

**Comment by nventuro** [comment]
The issue is not in OpenZeppelin: we thoroughly test every single commit to the repository, not just the fact that it compiles but also correctness. You can find the results of the latest test run [here](https://travis-ci.org/OpenZeppelin/openzeppelin-solidity/jobs/422942019).

From the error message you posted, it looks like there's something wrong with your setup - most likely, you're using an old compiler version that fails to correctly parse the `emit` inside the OpenZeppelin code. In any case, you shouldn't be importing code directly from GitHub: take a look at the [getting started guide](https://github.com/OpenZeppelin/openzeppelin-solidity#getting-started) for information on how to setup your project using an actual released version.

**Comment by PShivam92** [comment]
Im writing it in RemixIDE i think this is how we import in remix
