### ISSUE TITLE
Not able to set conversion rate in decimals

### ISSUE THREAD

**Issue by madan-ideas2it** [OpenZeppelin/openzeppelin-solidity#1278]
In my case, i want to give 100.5 tokens for 1 ether, in such case i want to set the rate in Crowdsale.sol as 100.5. But it is accepting only whole numbers and storing only 100.

You claim to set rate only for wei to token unit, and not for ether to token

But conversion rate is always the same for any conversion.

Example: If i want 100.5 tokens for 1 ether, this is same as

100.5 * 10^18 units for 1 * 10^18 weis

Hence i somehow need conversion rate in decimals

I know solidity doesnot support decimal points but how to make my case work because it is very obvious the conversion rate needs to be fluctuated in decimals based on market price

**Comment by nventuro** [comment]
100.5 tokens for 1 ether is *not* the same as '100.5 * 10^18 units for 1 * 10^18 weis', the decimals are only used when amounts are displayed (e.g. on exchanges), none of the math takes them into account, precisely to allow fixed point math to work.

If what you want to do is have an exchange rate of 100.5 of your token units to 1 wei, then I'm afraid that's not possible, since the EVM only supports integers: this is fundamental Ethereum design decision that cannot be worked around.
