### ISSUE TITLE
about ERC721 standard

### ISSUE THREAD

**Issue by flyq** [OpenZeppelin/openzeppelin-solidity#1337]
## 🎉 Description
- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.
- [x] personal confuse question.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

In ERC721, why is there no returns (bool) in  transferFrom function like ERC20? 
```
    function transferFrom(address _from, address _to, uint256 _tokenId) public;
```

and why delete the transfer function?
```
    function transfer(address _to, uint256 _tokenId) public;
```
    

## 👍 Other Information
I am confuse, thx.

**Comment by nventuro** [comment]
Hey there @flyq! Our 721 implementation follows the [official specification](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md#specification), in which there is no `transfer` function, and `transferFrom` returns nothing. You can read more over there on the rationale behind this decision, but `transferFrom` probably returns nothing because the people who wrote the spec decided it was better to simply revert on error.

**Comment by flyq** [comment]
Thx
