### ISSUE TITLE
ERC20Mintable should not allow for minting to end

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1348]
The current contract has the following function:

```
  function finishMinting()
    public
    onlyMinter
    onlyBeforeMintingFinished
    returns (bool)
  {
    _mintingFinished = true;
    emit MintingFinished();
    return true;
  }
```

This, in effect, is equivalent to giving all minters permission to remove all other minters (and themselves) from the minter group, which goes against the minimal assumption model we've been following for the Roles feature: we should get rid of it.

**Comment by frangio** [comment]
An interesting thing to note is that this function was necessary when the minter was the owner, because they might have wanted to keep ownership for other things (e.g. pausing), and still give token holders the guarantee that minting was no longer possible. With the new granular permissions, this problem is no longer there. The minters can renounce minting to achieve a similar effect.
