### ISSUE TITLE
Code Styling: ERC20.sol amount vs value

### ISSUE THREAD

**Issue by mswezey23** [OpenZeppelin/openzeppelin-solidity#1372]
🎉 Description
🖋 This is a styling report.
📝 Details

Use `value` vs `amount` for consistency. All other functions are using `value`

```
  function _mint(address account, uint256 amount) internal {
   
  function _burn(address account, uint256 amount) internal {

  function _burnFrom(address account, uint256 amount) internal {
```

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol

Suggestion:

Use `value` to be consistent across the board. Should check other contracts to be sure it's standardized across all contracts.

**Comment by frangio** [comment]
Yikes, you're right we should be consistent on this. Thanks!

(Thinking out loud here.) At some point I used to prefer `amount` for tokens and `value` for ether (as in `msg.value`), but now that I think about it, "token amount" has always been very ambiguous because people expect it to not include the decimal digits, yet the smart contract needs all of the decimal digits. Maybe `value` is less ambiguous, precisely because it carries over the intuition from `msg.value` being expressed in wei.

**Comment by Aniket-Engg** [comment]
I think `value` will be good for consistency. If it is final, I can work on it. Please let me know @mswezey23

**Comment by nventuro** [comment]
@Aniket-Engg feel free to open a PR with ths change! :)
