### ISSUE TITLE
Mocks missing from the npm package

### ISSUE THREAD

**Issue by scoriiu** [OpenZeppelin/openzeppelin-solidity#1405]
According to the specifications of the npm package, the contract dir should also include:
"mocks - A collection of abstract contracts that are primarily used for unit testing. They also serve as good usage examples and demonstrate how to combine contracts with inheritence (<--spelling mistake) when developing your own custom applciations. (<--spelling mistake)"

This can be useful if one needs to run the zeppelin tests.

**Comment by nventuro** [comment]
Hi @scoriiu, thanks for reporting this! As per our [releasing guide](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/RELEASING.md), mocks should be left out of the package, since they contain unsafe code that is only suitable for our tests. The npm package description is the one that's incorrect, I'll be fixing that shortly.

If your intent is to run the OpenZeppelin test suite, then you should clone the project directly, since otherwise you'll also be missing our dev dependencies (e.g. `chai-bignumber`).

And feel free to open PRs when you find a typo! Those are always helpful :)

**Comment by scoriiu** [comment]
Hi @nventuro!

Thanks for the quick answer. I guess that I will stick to keeping zeppelin as a submodule.

Cheers!
Solomon

**Comment by scoriiu** [comment]
1. Incorporating the zeppelin tests as part of my test suite, as an extra safe guard.
2. I use some of the mocks in my tests directly.
