### ISSUE TITLE
lifecycle_Destructible.html but no Destructible.sol

### ISSUE THREAD

**Issue by godfreyhobbs** [OpenZeppelin/openzeppelin-solidity#1486]
There is a doc https://openzeppelin.org/api/docs/lifecycle_Destructible.html but there is no code in 2.0

**💻 Environment**
Just looking at your docs

This is in 2.0 docs.
**📝 Details**
2.0 does not have a lifecycle_Destructible contract but there is still documentation.

Personally I would like to see a lifecycle/Destructible.sol in v2.0.  I think it is a useful tool especially when doing iterations on testnet.

Just view https://openzeppelin.org/api/docs/lifecycle_Destructible.html then click on the link `Source: lifecycle/Destructible.sol` it opens up v1.12 NOT v2.0.

**🔢 Code to reproduce bug**

Look at the following, Destructible is not there:
https://github.com/OpenZeppelin/openzeppelin-solidity/tree/release-v2.0.0/contracts/lifecycle

**Comment by Aniket-Engg** [comment]
Please Have a look: https://github.com/OpenZeppelin/openzeppelin-eth/issues/25

**Comment by frangio** [comment]
Hi @godfreyhobbs! It looks like a bug in our docs generation. That page shouldn't exist; note that `Destructible` is not in [the sidebar for 2.0.0](https://openzeppelin.org/api/docs/crowdsale_Crowdsale.html).

Please take a look at https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1254 for the reasons for removing `Destructible`.

> I think it is a useful tool especially when doing iterations on testnet.

This is a very interesting point. We removed the feature because we consider it dangerous on mainnet, but I can see how it can be useful in some testing workflows. I'll keep this in mind but unfortunately the other point is kind of a deal breaker.

**Comment by nventuro** [comment]
The docsite has been revamped, and this bug fixed.
