### ISSUE TITLE
increaseAllowance and decreaseAllowance should not be in ERC20.sol

### ISSUE THREAD

**Issue by 1nfinite** [OpenZeppelin/openzeppelin-solidity#1494]
I notice that both `increaseAllowance` and `decreaseAllowance` is public external function in the ERC20.sol.
Shoudn't it be internal function (like the mint() and burn()) as increaseAllowance and decreaseAllowance is not standard ERC20?

What is the justification to this.

Also, what is the justification to not enforce `require(_value == 0 || allowed[msg.sender][_spender] == 0);` in the approve() function to mitigate the race condition instead only just write a comment on there.

Any comments on how the consensus is reach here ?

**Comment by barakman** [comment]
@1nfinite:
This is not a part of the ERC20 standard, and you might notice that indeed, it is not declared in the `IERC20` interface.
The reason these functions where added is to provide a workaround for the front-running breach embedded in the `approve` function (more accurately, in an improper usage of the `approve` function).
Such front running can be performed if someone calls `approve` with a non-zero value, and then again with a non-zero value.
One solution is to be sure that you call this function with "alternating" values (i.e., non-zero, zero, non-zero, zero). Since this usage is not dictated by the ERC20 standard, it cannot be imposed by the provider (OpenZeppelin in this case). Hence, an extension was added in `ERC20.sol`, which allows the user to safely work-around the problem.
You can read more about the *ERC20 Approve Issue* [here](https://blog.smartdec.net/erc20-approve-issue-in-simple-words-a41aaf47bca6).

**Comment by nventuro** [comment]
Hello @1nfinite! `increaseAllowance` and `decreaseAllowance` are, as @barakman said, extensions end-users may use to more safely manage their tokens (assuming they know the functions are available in the contract), as can any contracts that interact with a known token (e.g. a crowdsale, but not an ERC20 exchange). We do provide the `SafeMath` library for this scenario though, which [adds that very same check](
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.0.0/contracts/token/ERC20/SafeERC20.sol#L47).

`approve` cannot enforce that requirement because the standard explicitly disallows doing so: see [here](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/438) for the discussion that prompted us removing it from OpenZeppelin.

**Comment by lusuo9** [comment]
OMG, I am just scammed by this method, the scammer sent me a link to click, and then increaseAllowance is called: https://www.oklink.com/bsc/tx/0x8f2c1f49087c06edb3bfa1d43a5181d9904d936b2c771faf99e3a9727d467d5c

And then my USDT was transferred: https://www.oklink.com/bsc/tx/0xd5400611185ba0529b69d35288194fe81e358ad42389b5d2ae1ee8d60ff40c23

So sad. I suggest to limit the use this method for scamming.

**Comment by barakman** [comment]
This function can only increase the allowance of the account which has signed a transaction of executing it.

So it is by no means a "scam function" as you've called it.

The scam here likely involved stealing your account's private key, and then using it in order to sign that transaction.

So sad. I suggest to think twice before clicking a link which you are not familiar with.
