### ISSUE TITLE
Various question on ReentrancyGuard usage

### ISSUE THREAD

**Issue by 1nfinite** [OpenZeppelin/openzeppelin-solidity#1495]
I am looking at the ReentrancyGuard (latest master branch) and its implementation.
There are a few questions that I would like to know.

1) Is it advisable to still use ReentrancyGuard in even if i adhere to check effects interaction pattern strictly in my function or it is fine that it is used together to complement check effects interaction pattern.

2) Is there scenario where reentrancy attack can still occur even if check effects interaction pattern is adhere?

3) Do i still need to use check effects interaction pattern if i use ReentrancyGuard?

4) What are the disadvantages of using ReentrancyGuard other than imposing higher gas fee? (Eg: deadlocking the contract as shown in [here](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/335), not sure if it still applies on latest code)

5) On what level does ReentrancyGuard guard the reentrancy?
For example, does it guard at function level (based on function call - _guardCounter will increase per function call by anyone), user per function level (based on msg.sender and function call) or how is it work?

**Comment by nventuro** [comment]
Generally, for simple contracts the checks-effects-interaction pattern will be sufficient. Things get a bit muddy once you add inheritance, external calls, etc. into the mix (as is the case with our `Crowdsale`'s `buyTokens`). Even if you do use `ReentrancyGuard`, I'd still attempt to adhere to that pattern, if only because I find it makes reasoning about execution flow easier.

The only disadvantage that I know of (other than added gas costs) is that only one `nonReentrant` function may be executed at any given time, that is, a `nonReentrant` function cannot call a different one with the same modifier (i.e. the mutex is global across the whole contract). This can be worked around by creating `nonReentrant` `external` functions that act as wrappers to `internal` functions containing the actual logic, but is sort of annoying. 

Hope this helps!
