### ISSUE TITLE
Keep master branch up to date with NPM package

### ISSUE THREAD

**Issue by nklipa13** [OpenZeppelin/openzeppelin-solidity#1621]
It happened for me few times that I'm looking into code on Github and its not same to what I see in NPM package and I understand that you are using master branch for developing but maybe it would be good to switch to `dev` branch for developing and to keep master up to date with NPM package as I think there is enough people looking at Github code and expecting that code to be in their NPM package

**Comment by nventuro** [comment]
This has been discussed a couple times already I think: I tend to agree with your stance (`master` is the latest stable release, `dev` undergoes frequent changes). If I recall correctly, the main argument against this is that PRs will be made by default against `master` instead of `dev`, requiring users and maintainers to double check that the target is correct (though I'd expect there to be a setting in GitHub to change this behavior).

There's also the point that people shouldn't really be looking at code on GitHub unless it's from a specific release tag (we've seen tons of tutorials, Remix guides, etc., indicating to simply clone master).

**Comment by frangio** [comment]
@nklipa13 My guess is that this was particularly annoying in the past few months given that there were a lot of big changes like the migration to Solidity 0.5 that weren't in `master` for a long time. This was totally exceptional because it caught us a bit unprepared. We've learned from that experience and a few others and I'm confident it won't happen again. :slightly_smiling_face:

We're reluctant to change the default branch to something other than the development branch because of the overhead it will cause for contributors and maintainers, as @nventuro explained, and we believe reducing that overhead should be the priority in the repository.

I don't think this will be such a big problem from now on, but please let us know if it does come up as an annoyance again!

**Comment by nklipa13** [comment]
@nventuro @frangio thanks for quick replies, maybe a good compromise would be to have one branch that is `last_release` or something like that? I think that can solve both problems, just put in readme that code from current NPM package is on that branch and that master branch is used for developing?
