### ISSUE TITLE
TokenVesting :: Is there any specific reason why _releasableAmount has to be private?

### ISSUE THREAD

**Issue by valerioleo** [OpenZeppelin/openzeppelin-solidity#1673]
**🧐 Motivation**
Simplify the interaction with TokenVesting

**📝 Details**
Directly reading the releasable amount can be very helpful to build a UI. At the moment, to calculate the releasableAmount, it is necessary to get all the necessary variables one by one and make the calculation. If `_releasableAmount` was public, it would be possible to query the releasable amount with only one query. Is there any specific reason why `_releasableAmount`is `private`? 

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/drafts/TokenVesting.sol#L152

**Comment by nventuro** [comment]
There is! An issue was identified by the Level K team during their audit of what became version v2.0.0, led by @cwhinfrey.

The original report read:
>TokenVesting.sol#L162​ - ​vestedAmount()​ returns a different amount if tokens areadded to the contract. The beneficiary could withdraw their currently vested tokens andsend them back to the contract in order to increase the amount returned byvestedAmount()​. Changing the function to ​vestedPercentage()​ and using that tocalculate ​releasableAmount()​ will prevent unexpected manipulation of the amountreturned by ​vestedAmount()​.

Instead of refactoring the contract as suggested, I chose to simply remove that function from the API in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1427, since the contract _does_ work correctly as is, and we have plans to eventually replace it.

You can find the final audit report [here](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.2.0-rc.1/audit/2018-10.pdf).

**Comment by valerioleo** [comment]
Amazing, thanks for the explanation. I'll look forward to seeing the `vestedPercentage()`. 👍
