### ISSUE TITLE
ERC20Vestable.sol

### ISSUE THREAD

**Issue by djenning90** [OpenZeppelin/openzeppelin-solidity#1674]
My apologies for probably not posting in the right place (I did poke around a bit but didn’t see the obvious place for this type of post). Any guidance will be appreciated.

I’m working on a smart contract for my project’s ICO to support start/cliff/duration-style vesting tokens, written as an ERC20 trait contract. Tokens can be granted by a grantor role, but can only be spent by the holder once vested. This capability may be useful for projects having investors or employees compensated in tokens.

I’m new to solidity and while learning I stumbled upon openzeppelin-solidity, and very much like what I’ve seen here. So I decided to adopt this group’s practices because they’re aligned with mine.

I’ve developed my ERC20-style contract so that it can be applied to another contracts, implementing specifically the needed capabilities around granting and vesting of tokens.

I have been working to this group’s standards to the best of my understanding, in hopes I might be able to contribute my work here, as others may find it useful.

What is the next step? Do I create an ERP or it’s equivalent requesting the capability, then open a discussion about it? I’ve completed the work needed for my project including thorough unit testing, and for my project, my work is done. But I realize additional work will likely be needed here, and my work may not be submittable in its current form without working with this group to generate consensus around how it should look.

Your guidance and feedback are welcome. Please suggest how best I should proceed. Thanks!

**Comment by Skyge** [comment]
Congratulations on finding the OpenZeppelin, just like what you said 
```
I’ve developed my ERC20-style contract so that it can be applied to another contracts, 
implementing specifically the needed capabilities around granting and vesting of tokens.
```
If you think this is a new feature that has never be implemented before, maybe you can make a document at here: https://github.com/ethereum/EIPs/,  at here, you will find there has existed some EIPs, so you should find out is there a similar EIP like yours. Owing to your roughly described, I am not sure if this is a new feature.
Thanks for your efforts!

**Comment by nventuro** [comment]
Hi there @djenning90! Have you looked at our [`TokenVesting`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.1.3/contracts/drafts/TokenVesting.sol) contract? It decouples the token from the vesting, so that there are no restrictions placed upon it, which I think is pretty neat (considering the vesting period should be short-lived when compared to the actual token usage).

We're also gathering feedback regarding vesting scheme requirements, since that contract isn't flexible enough to account for some real-life scenarios: read [here](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1214) for some initial ideas, and share your feedback!

**Comment by djenning90** [comment]
Thank you all for gently directing me to the right place. I'm learning how best to use these forums and really appreciate your help. Got a conversation going over in the TokenVesting contract thread.

I'll close this issue now.
