### ISSUE TITLE
ERC20Burnable functions do not returns (bool)

### ISSUE THREAD

**Issue by naddison36** [OpenZeppelin/openzeppelin-solidity#1688]
The `burn` and `burnFrom` functions on `ERC20Burnable` do not return a `bool` like other OZ ERC20 function. eg `ERC20Mintable.mint`
Is there a reason for this? Or has this simply been missed?

When I call `burn` from another contract, I'd like to check that the function call was successful by wrapping it in a `require`. This is not possible when `burn` does not return a `bool`.

**💻 Environment**

OpenZeppelin v0.2.2

**Comment by Skyge** [comment]
Yeah, it will not return a `bool` indeed, because the [contract](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20Burnable.sol#L14 ) does not provide a return value, but it will trigger an event, maybe you can try to solve with it.

**Comment by naddison36** [comment]
It's easy to fix. Shall I submit a PR?

**Comment by Skyge** [comment]
Just like what you said, `It's easy to fix.`, so I have already made a PR. Thanks for your help!

**Comment by nventuro** [comment]
Hey there @naddison36, @Skyge, thank you both for your help!

In OpenZeppelin, we adopt the convention that functions `revert` when encountering an error condition, as opposed to returning an error value. We believe this is safer, since it is very easy to forget to handle an error, which may have catastrophic consequences. Because of this, a call to `burn` will either succeed, or revert.

The fact that `ERC20Mintable` _does_ return a boolean value is a mistake we should correct, but this is sadly a breaking change, and will therefore be postponed until v3.0 comes out.
