### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by SriDraco** [OpenZeppelin/openzeppelin-solidity#1790]
Issue: 404 errors from links in several different files.

What I was trying to do: 

1. Follow the links in [the next steps in get-started.md](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/get-started.md#next-steps)
2. Follow the links (except selfdestruct()) in [access-control.md](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/access-control.md)
3. Follow the links in [crowdsales.md](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/crowdsales.md)
4. Follow the internal repo links in [tokens.md](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/tokens.md)
5. Follow the links in [utilities.md](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/utilities.md)

What happened instead: 
1. 404 error due to links missing file extensions
2. 404 errors all due to the links pointing to [/docs/api](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/docs/api/) (same with 3, 4, and 5)

Fix:
1. Add .md to the links in the section
2. The files that are linked now _appear_ to be located under the [/contracts/](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts) directory in the repo.

**Comment by frangio** [comment]
Thanks for reporting these @SriDraco! In case you didn't know, these files are published at https://docs.openzeppelin.org, where all of these links work correctly. 

The ones that are missing file extensions can be fixed for browsing within GitHub. The ones that are pointing to /docs/api can't be fixed, we want to remove them but due to a limitation in solidity-docgen right now we can't.
