### ISSUE TITLE
UninitializedFunctionPointerInConstructor on pausable token

### ISSUE THREAD

**Issue by cokia** [OpenZeppelin/openzeppelin-solidity#1807]
**💻 Environment**
latest OpenZeppelin pausable token , solidity 0.5.0

**📝 Details**

I using openzeppelin pausable token with out modify, and i verify contract on ehterscan, and etherscan said solc bug's on my code.

![image](https://user-images.githubusercontent.com/24792377/59994805-2dd68000-9690-11e9-85c1-2d345266a4fc.png)

and i want to know about where is occurring 
https://etherscan.io/solcbuginfo?a=UninitializedFunctionPointerInConstructor
this bug on pausable token code.

**Comment by nventuro** [comment]
Hello @cokia, thanks for reporting this!

I think that warning only refers to the fact that the contract _could_ be vulnerable to that bug because of the Solidity version it was compiled with, not because of the code itself. 

`ERC20Pausable` only has internal function calls in `PauserRole`'s constructor, but there are no function pointers involved, so I don't see how we could run into that bug. And in any case, our test suite would've probably caught such a scenario if it occured, so I think that's a false-positive.

**Comment by cokia** [comment]
thanks for your comment 👍
