### ISSUE TITLE
ERC223 implementation.

### ISSUE THREAD

**Issue by Sparke2** [OpenZeppelin/openzeppelin-solidity#1813]
**🧐 Motivation**

ERC223 standard token implementation.

**📝 Details**

ERC223 token standard is one of the major token standards on Ethereum. There are some projects that rely on this token standard and I think that it is a good idea to provide a reference implementation at openzeppelin token list.

**Comment by frangio** [comment]
Thank you for the suggestion @Sparke2.

Some previous discussion about ERC223 in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/512 and https://github.com/OpenZeppelin/openzeppelin-solidity/issues/346.

The major issue that we have is that the ERC has never been finalized. The document is still technically a draft. Our current preference is towards not including ERCs that are drafts, because they cause problems for our stability guarantees. We do have some draft contracts currently in our offering, but we would like to promote them to stable contracts soon.

If there are projects relying on ERC223, I would encourage those projects to push for making the ERC final.

**Comment by nventuro** [comment]
Closing for the reasons outlined above. We're still open to including such a standard, if the design moves forward and is finalized.
