### ISSUE TITLE
Crowdsale contract vulnerable to "fund recycling" attack

### ISSUE THREAD

**Issue by vadimkerr** [OpenZeppelin/openzeppelin-solidity#443]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L88
This comment should warn user that in default implementation forwardFund function can cause situation when owner can cheat the system by recycling ether trough the contract.

**Comment by veox** [comment]
## Ref

I've suggested in [a thread on /r/ethdev](https://www.reddit.com/r/ethdev/comments/6zvyu4/openzeppelin_crowdsale_contract/) this be reported here.

In particular, I wrote [this](https://www.reddit.com/r/ethdev/comments/6zvyu4/openzeppelin_crowdsale_contract/dmykd4s/), citing a slightly more verbose [exploit description](https://www.reddit.com/r/ethdev/comments/6zvyu4/openzeppelin_crowdsale_contract/dmyib5b/).

### Summary

If `Crowdsale` is used unmodified, and the benefactor address `wallet` does not forbid withdrawal at least until the end of the crowdsale, then the operator(s) of `wallet` can "bounce" the funds back to the crowdsale, artificially increasing their share of tokens for no ether cost (other than gas). This is exacerbated if the token sale is uncapped.

The above is an underhanded way for (imaginary) uncanny crowdsale operators to gain a larger share of tokens than they would be claiming, for example, in marketing materials. Detecting it requires (manual) vigilance by other parties, while the sale is on-going, which can not be guaranteed.

### Improvements

Code-wise, there is no way around it ("works as expected"). It can be made less severe by making the function's comment less suggestive, and more of a warning, in hopes that contract reviewers might spot it before the sale.

A separate "trickle funding" contract could also be provided, to act as the benefactor instead of a multi-sig wallet.

**Comment by veox** [comment]
In other words, contract use guidelines should suggest that either:

* the function _must_ be overridden to check that there's no "funding loop"; or
* the benefactor contract _must not_ allow withdrawal of ether until the end of the crowdsale.

There could possibly also be a guide for auditors or crowdsale participants, that would urge to check for the above; but I'm not sure if such a measure can be efficient.

**Comment by miohtama** [comment]
"The benefactor contract must not allow withdrawal of ether until the end of the crowdsale" - this only concerns cases where there is a minimum funding goal. If the crowdsale has been success I do not see a problem with an early withdrawing the funds. 

This is especially beneficial to the token sale organizers and token holders to to convert some ETH immediately and diverse assets under the downward market conditions, so that they can get the maximum value for the project they support.

**Comment by frangio** [comment]
Thanks for the comments @veox and @vadimkerr! I agree with all of it.

Have you seen the [`RefundVault`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/RefundVault.sol) contract that `RefundableCrowdsale` uses? We could add a similar contract as a middle step for funds in general.

**Comment by veox** [comment]
Ah!.. Yes, `Vault` sounds like the right kind of allegory.

-----

Somewhat OT:

`RefundVault` would need a way to receive `deposit()`s from `Crowdsale`, meaning either the `Vault` being owned by `Crowdsale` (bad idea IMO), or removing the `onlyOwner` modifier in favour of an `onlyAllowedSenders`.

With the above change, time locks (e.g. with reenrant `view` calls to check if `Crowdsale` has ended), drip-funding instead of everything-at-once, or any other fancy schemes can be implemented by inheriting the `RefundVault`, and overriding appropriate functions.

**Comment by frangio** [comment]
But "drip-funding" for example would be unrelated to refunds, so I don't see it being implemented as a subclass of `RefundVault`.

**Comment by veox** [comment]
Yup! That was a random OT rant. ;)

**Comment by maraoz** [comment]
Additional discussion on this topic: https://blog.zeppelin.solutions/handling-crowdsale-funds-securely-c348467da74c

**Comment by nventuro** [comment]
Indeed, a `RefundCrowdsale` doesn't have this issue due to using a `RefundEscrow`. We're discussing extending the `Escrow` model in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1099.

**Comment by nventuro** [comment]
https://github.com/OpenZeppelin/openzeppelin-solidity/issues/529 presented a related requirement.

**Comment by nventuro** [comment]
After giving this some more thought, I now believe this is out of scope of the baseline `Crowdsale` contract (on which there's no concept of the crowdsale 'ending' due to a goal being reached, the funding window being closed, etc.). Such a feature can be implemented by passing an `Escrow` as the crowdsale wallet, but we cannot force this without fundamentally changing how the current model works.

Given that the tools exist to properly and safely develop this, I'm closing the issue and marking as won't fix. A dishonest fund raise will not be impeded by OpenZeppelin holding honest code.
