### ISSUE TITLE
create tutorials for documentation

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#63]

**Comment by frangio** [comment]
A quick update. A couple tutorials have been written by @gustavoguimaraes:
- [Setting Up a Bug Bounty Smart Contract with OpenZeppelin](https://blog.zeppelin.solutions/setting-up-a-bug-bounty-smart-contract-with-openzeppelin-a0e56434ad0e)
- [How To Create Token and Initial Coin Offering Contracts Using Truffle + OpenZeppelin](https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6)

**Comment by elopio** [comment]
We have the `guides` tag in the blog: https://blog.zeppelin.solutions/guides/home
I'm leaving this open because we are planning some improvements on the docs site, so this will be a reminder that it should include a tutorials section or at least a link to these guides.

But I think that it would be better to file individual issues for each tutorial that we want to add to the docs. I'll be back later to close this :)

**Comment by nventuro** [comment]
We have some guides in [the docsite](https://docs.openzeppelin.org/docs/get-started.html), and the undergoing revamp will make it easier for everyone to contribute to these so-called 'mini-readme' guides.
