### ISSUE TITLE
Whitelisting as function modifiers

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#8]
Implement function modifiers that only allow calls from a whitelist of addresses/contracts
See Whitelist at http://vessenes.com/we-need-some-best-practices-for-smart-contracts/

**Comment by rudygodoy** [comment]
I'm working on this, by now I've created a separate project so that it's easier to test in isolation. I've implemented the white list as a switch so that addresses can be enabled/disabled at will, this would allow different use cases commented in the article. Once I feel comfortable about the implementation I'll integrate in my branch then do the PR. Comments are welcome.

https://github.com/rudygodoy/whitelistToken/blob/master/contracts/WhitelistToken.sol#L12

**Comment by frangio** [comment]
The idea would be to provide general-purpose function modifiers that can be used in any smart contract. Not just a specific token implementatioṇ like I saw in your repo; not sure if that was just to test the idea.

I've begun experimenting with something very similar to this that allows more than one whitelist. Please see [my `feature/roles` branch](https://github.com/frangio/zeppelin-solidity/blob/feature/roles/contracts/Roles.sol). There are no examples though.

**Comment by rudygodoy** [comment]
Hi @frangio, yes I understand the goal it aims. I’ve built a token so that I’m able to validate my implementation with the use cases commented in the article. 
I've also thought that this could be a lib, but my plan was to do that as the next improvement.
Right now I’m working on validating a third contract accessing the whitelisted-contract's functions. I believe that it would fit very well with the proxy libs.

**Comment by ajsantander** [comment]
hey @rudygodoy 
did you have any luck with this?

**Comment by rudygodoy** [comment]
Hi, I did. It’s almost done. I plan to polish things out next week.

**Comment by feulf** [comment]
Any update on this? I'm creating my own version, in my contract, could be nice to have it as a separate library as part of Zeppelin.

```
    mapping (address => bool) public whitelist;

    modifier onlyWhitelistAddress() {
        require(whitelist[msg.sender] == true);
        _;
    }
      
    function addWhitelistAddress (address _address) public onlyOwner{
        whitelist[_address] = true;
    }
    
    function removeWhitelistAddress (address _address) public onlyOwner{
        whitelist[_address] = false;
    }
```

**Comment by rudygodoy** [comment]
Implementation for a whitelist in a contract it's basically trivial, most of the proposals are pretty much alike. The issue comes with the integration part since we would like to have it as a reusable modifier. Given that, I'm sharing some of the challenges to direct the discussion towards a smooth implementation. 

- The whitelist data structure has to be in the scope of the contract, so 
- With regards to decoupling the modifier from the contracts that want to implement whitelisting or their functions, there must be a way for them to know how to access their locally-shared access data structure and, if that's the case
- Developers would need to be aware of the previous assumptions, which can be overkill for OZ's goal of "ready to play" code base

The library's route could be useful for the shared data structure, however:
- The access data structure will be shared, that's the way how libraries are deployed, which is not something people would like to have for their own contract's implementation, and
- As with plain modifiers, the function modifier would need to know how to access that data structure

**Comment by feulf** [comment]
Cool. I'll use my own implementation for now as I've to move forward with our MVP, but I'm looking forward to using the OpenZeppelin implementation.

**Comment by rudygodoy** [comment]
I'm sharing my initial attempt, so people can comment. It works fine, no issues on remix as well. However, I'm having very weird issues with the integration tests for the `disable` and `check` methods for the skeleton contract (whitelisted). I haven't put much time debugging that problem. I'll keep you posted or just do the PR when everything is as I expect it to be.

```
pragma solidity ^0.4.11;

library Whitelist {
  
  struct List {
    mapping(address => bool) registry;
  }
  
  function add(List storage list, address _addr)
    internal
  {
    list.registry[_addr] = true;
  }

  function remove(List storage list, address _addr)
    internal
  {
    list.registry[_addr] = false;
  }

  function check(List storage list, address _addr)
    view
    internal
    returns (bool)
  {
    return list.registry[_addr];
  }
}

contract Whitelisted {

  Whitelist.List private _list;
  
  modifier onlyWhitelisted() {
    require(Whitelist.check(_list, msg.sender) == true);
    _;
  }

  event AddressAdded(address _addr);
  event AddressRemoved(address _addr);
  
  function Whitelisted()
  public
  {
    Whitelist.add(_list, msg.sender);
  }

  function enable(address _addr)
    public
  {
    Whitelist.add(_list, _addr);
    AddressAdded(_addr);
  }

  function disable(address _addr)
    public
  {
    Whitelist.remove(_list, _addr);
    AddressRemoved(_addr);
  }
  
  function isListed(address _addr)
  public
  view
  returns (bool)
  {
      return Whitelist.check(_list, _addr);
  }
}

contract WhitelistToken is Whitelisted {

  function onlyWhitelistedCanDo()
    onlyWhitelisted
    view
    external
  {    
  }

}

```

**Comment by cryptodegreeofficial** [comment]
hello can you help how to make this contract transferable?  I created a simple contract as practice.  Then when I try to send the token from creator wallet to another wallet it doesn't work.  It appears  the error like this ''cannot find the transfer events log checked sender  pls help.

**Comment by elopio** [comment]
There is a simple [WhitelistedCrowdsale](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/crowdsale/validation/WhitelistedCrowdsale.sol) that shows how to use modifiers to solve this, but is not a general solution for all contracts.
The [Role-Based Access Control contract has the onlyRole modifier](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/4a10f727c4756a8f6433f272a49e7a15db5e4b8f/contracts/ownership/rbac/RBAC.sol#L81) that generalizes this for all contracts and for many other use cases in addition to whitelists.

I'm closing this issue. Please reopen if there's something missing.

@shrugs would it make sense to update the WhitelistCrowdsale to use RBAC?

**Comment by elopio** [comment]
@cryptodegreeofficial check [Ownable](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/ownership/Ownable.sol)
