### ISSUE TITLE
checkAndCallSafeTransfer does not act as described

### ISSUE THREAD

**Issue by bee-irl** [OpenZeppelin/openzeppelin-solidity#908]
## checkAndCallSafeTransfer does not act as described

- [x] 🐛 This is a bug report.

## 📝 Details

On line 273 of ERC721BasicToken.sol (https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC721/ERC721BasicToken.sol#L273) the documentation says:

> The call is not executed if the target address is not a contract

However, later on, the code reads:

```
    if (!_to.isContract()) {
      return true;
    }
    bytes4 retval = ERC721Receiver(_to).onERC721Received(_from, _tokenId, _data);
    return (retval == ERC721_RECEIVED);
```
It seems that if the `_to` address is not a contract the function returns `true`. However the documentation states that the "call should not be executed" if the `_to` address is not a contract. What does that mean exactly?

Why does this function return `true` when the `_to` address is not a contract?

**Comment by frangio** [comment]
Hi @bee-irl, thanks for bringing this up.

The documentation isn't very clear. "The call should not be executed" refers to the `onERC721Received` call. As you can see in the snippet you pasted, this is indeed true.

The boolean return value is not well documented either, it says it is "whether the call correctly returned the expected magic value", but this only applies to the case when `_to` is a contract. As we can see in the use of `checkAndCallSafeTransfer` the boolean return value is used to verify success in both cases and revert otherwise.

https://github.com/OpenZeppelin/zeppelin-solidity/blob/77cc33fc5c4d0b0d03aec1d8bba77edc9a7196ae/contracts/token/ERC721/ERC721BasicToken.sol#L197

I think the name `checkAndCallSafeTransfer` should be improved. It isn't very good because the actual transfer is not done in this function. What is called is `onERC721Received`.

**Comment by bee-irl** [comment]
@frangio I'm a bit new to this, but, shouldn't `transferFrom` fail if `_to` is not a contract? Otherwise it's possible to send an ERC721 token to a `_to` address that won't be able to interact with it. Please let me know if I've misunderstood this somehow.

**Comment by frangio** [comment]
@bee-irl We have to refer to the [specification](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) for `safeTransferFrom`.

>When transfer is complete, this function checks if `_to` is a smart contract (code size > 0). If so, it calls `onERC721Received` on `_to` and throws if the return value is not `bytes4(keccak256("onERC721Received(address,uint256,bytes)"))`.

This means that `safeTransferFrom` should work just fine if `_to` is not a contract.

**Comment by bee-irl** [comment]
@frangio is it possible for a non-contract address to spend an ERC721 token?

**Comment by frangio** [comment]
Absolutely. A non-contract address can receive and send ERC721 tokens.
