### ISSUE TITLE
Implement noThrowCall for non-throwing calls

### ISSUE THREAD

**Issue by shrugs** [OpenZeppelin/openzeppelin-solidity#965]
## 🎉 Description

It'd be cool to implement `noThrowCall()` defined similarly to https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by frangio** [comment]
Closing this as it can be accomplished with Solidity `.call` and `abi.encodeWithSelector` for the call data. I believe in EIP 165 the function was implemented because at that point there was not non-assembly `staticcall` in Solidity.

Anyone interested in this may also be interested in https://github.com/ethereum/solidity/issues/6927.
