### ISSUE TITLE
Fix solidity version

### ISSUE THREAD

**Issue by subramanianv** [OpenZeppelin/openzeppelin-solidity#975]
## 🎉 Description

The solidity version in the contracts should be fixed instead of this version and above. 

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by shrugs** [comment]
hi @subramanianv can you talk more about why you think the solidity version should be pinned to a specific compiler?

**Comment by subramanianv** [comment]
Its a good practice to use exact solidity versions. It makes it easy for compiling and verifying contracts on etherscan. Also what version should we use when you merge contracts that have different versions ?

**Comment by frangio** [comment]
@subramanianv This is something we've considered a few times. I really don't see how it would make it easier for compiling and verifying, though. For verifying there is additional obstacles such as compilation parameters which are not specified in the source code pragma.

We think it makes sense for a library such as OpenZeppelin to use `^` version specifiers because it allows our users to compile their contracts with newer Solidity versions without us having to rush to update with every Solidity release. In fact we have a policy of waiting at least a month before updating the Solidity version we use for development, to give some time for possible bugs in the compiler to be discovered. 

The Solidity team is quite commited to backwards compatibility, so we trust that it is fine to allow users to use semver-compatible greater versions.

We would certainly recommend, however, for end-users to pin the compiler version they use during development.
